sudo: enabled
dist: xenial
language: python
python: 3.6

before_install:
  # Install node.js following instructions from
  #   https://nodejs.org/en/download/package-manager/
  - sudo apt install curl
  - curl -sL https://deb.nodesource.com/setup_11.x | sudo bash -
  - sudo apt install nodejs
  # Install ODBC development libraries
  - sudo apt install unixodbc-dev


install:
  # Install node.js dependencies
  - npm install
  # Install python dependencies
  - pip install -r requirements-dev.txt

script:
  # Run all pytest unit tests
  - python -m pytest -v tests --cov misinformation --cov-report term-missing
  # Run pyflakes for error detection
  - pyflakes *.py misinformation tests
  # Check PEP8 compliance (ignoring long lines)
  - pycodestyle --statistics --ignore=E501 --count *.py misinformation tests