# Spider configurations for each website to be crawled

conservativehq.com:
  site_name: 'conservativehq.com'
  start_url: 'http://conservativehq.com/exclusives'
  follow_url_path: 'exclusives'
  article_url_path: 'article/'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'content'
  metadata:
    title:
      select-method: 'xpath'
      select-expression: '//h1[@class="title"]/text()'

federalistpress.com:
  site_name: 'federalistpress.com'
  start_url: 'http://federalistpress.com/category/all-stories'
  follow_url_path: 'category/all-stories/page/'
  article_url_xpath: '//h2[@class="entry-title"]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'entry-content'
  metadata:
    title:
      select-method: 'xpath'
      select-expression: '//h1[@class="entry-title"]/text()'

palmerreport.com:
  site_name: 'palmerreport.com'
  start_url: 'https://palmerreport.com/category/analysis/'
  follow_url_path: 'category/analysis/page/'
  article_url_xpath: '//h2[@class="fl-post-title"]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'fl-post-content'
  metadata:
    title:
      select-method: 'xpath'
      select-expression: '//h1[@class="fl-post-title"]/text()'

# TODO: Test from US IP address (get 403 from UK and Slovakia)
patriotnewsdaily.com:
  site_name: 'patriotnewsdaily.com'
  start_url: 'http://patriotnewsdaily.com/category/all-conservative-news/'
  follow_url_path: 'category/all-conservative-news/page/'
  article_url_xpath: '//h2[@class="post-title"]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'entry'

# TODO: Enhance spider to follow relative links
# TODO: Find good configurable value for identifying article body DIV (no class)
#redstatewatcher.com:
#  site_name: 'redstatewatcher.com'
#  start_url: 'http://redstatewatcher.com/news.asp'
#  follow_url_path: 'news.asp\?page=\d*'
#  article_url_xpath: '//h1[@class="newsheaderpreview"]/a'
#  metadata_source: 'microdata'
#  article_search: 'paged'
#  article_element: 'div'
#  article_class: 'FIXME'

youngcons.com:
  site_name: 'youngcons.com'
  start_url: 'http://youngcons.com/category/politics/'
  follow_url_path: 'category/politics/page/'
  article_url_xpath: '//h3[contains(concat(" ",normalize-space(@class)," ")," entry-title ")]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'td-post-content'

addictinginfo.com:
  site_name: 'addictinginfo.com'
  start_url: 'http://addictinginfo.com/category/news/'
  follow_url_path: 'page/'
  article_url_xpath: '//h2[@class="entry-title"]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'entry-content'
  metadata:
    title:
      select-method: 'xpath'
      select-expression: '//h1[@class="entry-title"]/a/text()'

occupydemocrats.com:
  site_name: 'occupydemocrats.com'
  start_url: 'http://occupydemocrats.com'
  follow_url_path: 'page/'
  article_url_xpath: '//h3[@itemprop="headline"]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'entry-content'

davidwolfe.com:
  site_name: 'davidwolfe.com'
  start_url: 'https://www.davidwolfe.com/category/news/'
  follow_url_path: 'category/news/page/'
  article_url_xpath: '//h2[@class="entry-title"]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'entry-content'

# TODO: Get link extraction working. The issue is not the rel="bookmark" attribute of the <a> element containing
# the article href as both prisonplanet.com and empirenews.com crawl fine with the same attribute present
eyeopening.info:
  site_name: 'eyeopening.info'
  start_url: 'http://eyeopening.info/category/politics/'
  follow_url_path: 'category/politics/page/'
  article_url_xpath: '//h2[@class="entry-title"]/a' #FIXME? - Or fix LinkExtractor / use custom parse() method
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'entry-content'

globalresearch.ca:
  site_name: 'globalresearch.ca'
  start_url: 'http://globalresearch.ca/latest-news-and-top-stories'
  follow_url_path: 'latest-news-and-top-stories/page/'
  article_url_xpath: '//strong[@class="title"]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'content'

henrymakow.com:
  site_name: 'henrymakow.com'
  start_url: 'http://henrymakow.com/archives.html'
  follow_url_path: 'category/politics/page/'
  article_url_xpath: '//p[not(@class)]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'text-body'

gellerreport.com:
  site_name: 'gellerreport.com'
  start_url: 'http://gellerreport.com/category/atlas-articles/'
  follow_url_path: 'category/atlas-articles/page/'
  article_url_xpath: '//h2[@class="archive-entry-title"]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'entry-content'

prisonplanet.com:
  site_name: 'prisonplanet.com'
  start_url: 'http://prisonplanet.com/section/featured-stories/'
  follow_url_path: 'section/featured-stories/page/'
  article_url_xpath: '//div[@class="nArchiveHeader"]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'subarticle'

empirenews.net:
  site_name: 'empirenews.net'
  start_url: 'http://empirenews.net/category/politics/'
  follow_url_path: 'category/politics/page/'
  article_url_xpath: '//h1[@class="entry-title"]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'entry-content'

madworldnews.com:
  site_name: 'madworldnews.com'
  start_url: 'http://madworldnews.com/politics/'
  follow_url_path: 'politics/page/'
  article_url_xpath: '//h3[contains(concat(" ",normalize-space(@class)," ")," entry-title ")]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'entry-content'