
# Spider configurations for each website to be crawled
addictinginfo.com:
  site_name: 'addictinginfo.com'
  start_url: 'http://addictinginfo.com/category/news/'
  follow_url_path: 'page/'
  article_url_xpath: '//h2[@class="entry-title"]/a'
  article_search: 'paged'
  article:
    content:
      select-method: 'xpath'
      select-expression: '//div[@class="entry entry-content"]'
      match-rule: 'single'
    publication_datetime:
      select-method: 'xpath'
      select-expression: '//time[contains(concat(" ", normalize-space(@class), " "), " entry-date ")]/@datetime'
      match-rule: 'single'
    title:
      select-method: 'xpath'
      select-expression: '//meta[@property="og:title"]/@content'
      match-rule: 'first'
    byline:
      select-method: 'xpath'
      select-expression: '//meta[@name="author"]/@content'
      match-rule: 'first'

conservativehq.com:
  site_name: 'conservativehq.com'
  start_url: 'http://conservativehq.com/exclusives'
  follow_url_path: 'exclusives'
  article_url_path: 'article/'
  article_search: 'paged'
  article:
    content:
      select-method: 'xpath'
      select-expression: '//div[@class="node"]/div[@class="content"]'
      match-rule: 'single'
    title:
      select-method: 'xpath'
      select-expression: '//meta[@property="og:title"]/@content'
      match-rule: 'first'
    byline:
      select-method: 'xpath'
      select-expression: '//div[@class="field-item odd"]/text()'
      match-rule: 'first'
      warn-if-missing: 'False'
    publication_datetime:
      select-method: 'xpath'
      select-expression: '//div[@class="content"]/div[contains(concat(" ", normalize-space(@class), " "), " field ")]/div[contains(concat(" ", normalize-space(@class), " "), " field-items ")]/div[contains(concat(" ", normalize-space(@class), " "), " field-item ")]/text()'
      match-rule: 'single'
      datetime-format: 'MM/DD/YY'
      warn-if-missing: 'False'

empirenews.net:
  site_name: 'empirenews.net'
  start_url: 'http://empirenews.net/category/politics/'
  follow_url_path: 'category/politics/page/'
  article_url_xpath: '//h1[@class="entry-title"]/a'
  article_search: 'paged'
  article:
    content:
      select-method: 'xpath'
      select-expression: '//div[@class="entry-content"]'
      match-rule: 'single'
    title:
      select-method: 'xpath'
      select-expression: '//h1[@class="entry-title"]/text()'
      match-rule: 'first'
    byline:
      select-method: 'xpath'
      select-expression: '//span[@class="author vcard"]/a/text()'
      match-rule: 'single'
    publication_datetime:
      select-method: 'xpath'
      select-expression: '//time[@class="entry-date published updated"]/@datetime'
      match-rule: 'single'

federalistpress.com:
  site_name: 'federalistpress.com'
  start_url: 'http://federalistpress.com/category/all-stories'
  follow_url_path: 'category/all-stories/page/'
  article_url_xpath: '//h2[@class="entry-title"]/a'
  article_search: 'paged'
  article:
    content:
      select-method: 'xpath'
      select-expression: '//div[@class="entry-content"]'
      match-rule: 'single'
    title:
      select-method: 'xpath'
      select-expression: '//meta[@property="og:title"]/@content'
      match-rule: 'first'
    byline:
      select-method: 'xpath'
      select-expression: '//div[@class="post-info"]//span[@class="author vcard"]//text()'
      match-rule: 'single'
    publication_datetime:
      select-method: 'xpath'
      select-expression: '//span[@class="date published time"]/@title'
      match-rule: 'single'

gellerreport.com:
  site_name: 'gellerreport.com'
  start_url: 'http://gellerreport.com/category/atlas-articles/'
  follow_url_path: 'category/atlas-articles/page/'
  article_url_xpath: '//h2[@class="archive-entry-title"]/a'
  article_search: 'paged'
  article:
    content:
      select-method: 'xpath'
      select-expression: '//div[@class="entry-content"]'
      match-rule: 'first'
    title:
      select-method: 'xpath'
      select-expression: '//h1[@class="entry-title"]/text()'
      match-rule: 'single'
    byline:
      select-method: 'xpath'
      select-expression: '//div[@class="byline"]/a/text()'
      match-rule: 'single'
    publication_datetime:
      select-method: 'xpath'
      select-expression: '//time[@class="post-entry-time"]/@datetime'
      match-rule: 'single'

palmerreport.com:
  site_name: 'palmerreport.com'
  start_url: 'https://palmerreport.com/category/analysis/'
  follow_url_path: 'category/analysis/page/'
  article_url_xpath: '//h2[@class="fl-post-title"]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'fl-post-content'
  article:
    content:
      select-method: 'xpath'
      select-expression: '//div[@itemprop="text"]'
      match-rule: 'single'
    title:
      select-method: 'xpath'
      select-expression: '//meta[@property="og:title"]/@content'
      match-rule: 'single'
    byline:
      select-method: 'xpath'
      select-expression: '//span[@class="fl-post-author"]/a/text()'
      match-rule: 'single'
    publication_datetime:
      select-method: 'xpath'
      select-expression: '//meta[@property="article:published_time"]/@content'
      match-rule: 'single'

# TODO: Test from US IP address (get 403 from UK and Slovakia)
patriotnewsdaily.com:
  site_name: 'patriotnewsdaily.com'
  start_url: 'http://patriotnewsdaily.com/category/all-conservative-news/'
  follow_url_path: 'category/all-conservative-news/page/'
  article_url_xpath: '//h2[@class="post-title"]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'entry'
  article:
    content:
      select-method: 'xpath'
      select-expression: '//div[@class="entry"]'
      match-rule: 'single'
    title:
      select-method: 'xpath'
      select-expression: '//meta[@property="og:title"]/@content'
      match-rule: 'first'
    byline:
      select-method: 'xpath'
      select-expression: '//div[@class="vcard author"]//a/text()'
      match-rule: 'single'
    publication_datetime:
      select-method: 'xpath'
      select-expression: '//span[@class="updated"]/text()'
      match-rule: 'single'
      datetime-format: 'YYYY-MM-DD'

# TODO: Enhance spider to follow relative links
# -- JR: I think this is already done
redstatewatcher.com:
  site_name: 'redstatewatcher.com'
  start_url: 'http://redstatewatcher.com/news.asp'
  follow_url_path: 'news.asp\?page=\d*'
  article_url_path: 'article.asp\?id=\d*'
  metadata_source: 'microdata'
  article_search: 'paged'
  article:
    content:
      select-method: 'xpath'
      select-expression: '//div[@class="container" and div[@class="row"]]'
      match-rule: 'single'
    title:
      select-method: 'xpath'
      select-expression: '//meta[@property="og:title"]/@content'
      match-rule: 'single'

youngcons.com:
  site_name: 'youngcons.com'
  start_url: 'http://youngcons.com/category/politics/'
  follow_url_path: 'category/politics/page/'
  article_url_xpath: '//h3[contains(concat(" ", normalize-space(@class), " "), " entry-title ")]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'td-post-content'
  article:
    content:
      select-method: 'xpath'
      select-expression: '//div[@class="td-post-content"]'
      match-rule: 'single'
    title:
      select-method: 'xpath'
      select-expression: '//meta[@property="og:title"]/@content'
      match-rule: 'single'
    byline:
      select-method: 'xpath'
      select-expression: '//span[@itemprop="author"]/meta[@itemprop="name"]/@content'
      match-rule: 'single'
    publication_datetime:
      select-method: 'xpath'
      select-expression: '//meta[@itemprop="datePublished"]/@content'
      match-rule: 'single'

occupydemocrats.com:
  site_name: 'occupydemocrats.com'
  start_url: 'http://occupydemocrats.com'
  follow_url_path: 'page/'
  article_url_xpath: '//h3[@itemprop="headline"]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'entry-content'
  article:
    content:
      select-method: 'xpath'
      select-expression: '//div[@itemprop="articleBody"]'
      match-rule: 'single'
    title:
      select-method: 'xpath'
      select-expression: '//meta[@property="og:title"]/@content'
      match-rule: 'first'
    byline:
      select-method: 'xpath'
      select-expression: '//span[@class="author-name vcard fn author"]/a/text()'
      match-rule: 'single'
    publication_datetime:
      select-method: 'xpath'
      select-expression: '//time[@class="post-date updated"]/@datetime'
      match-rule: 'single'
      datetime-format: 'YYYY-MM-DD'

davidwolfe.com:
  site_name: 'davidwolfe.com'
  start_url: 'https://www.davidwolfe.com/category/news/'
  follow_url_path: 'category/news/page/'
  article_url_xpath: '//h2[@class="entry-title"]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'entry-content'
  article:
    content:
      select-method: 'xpath'
      select-expression: '//div[@class="entry-content"]'
      match-rule: 'single'
    title:
      select-method: 'xpath'
      select-expression: '//h1[@class="entry-title"]/text()'
      match-rule: 'first'
    byline:
      select-method: 'xpath'
      select-expression: '//span[@class="entry-author-name"]/text()'
      match-rule: 'single'
    publication_datetime:
      select-method: 'xpath'
      select-expression: '//time[contains(concat(" ", normalize-space(@class), " "), " entry-time ")]/@datetime'
      match-rule: 'single'

# TODO: Get link extraction working. The issue is not the rel="bookmark" attribute of the <a> element containing
# the article href as both prisonplanet.com and empirenews.net crawl fine with the same attribute present
eyeopening.info:
  ignore-multi-html-elements: 'False'
  site_name: 'eyeopening.info'
  start_url: 'http://eyeopening.info/category/politics/'
  follow_url_path: 'category/politics/page/'
  article_url_xpath: '//h2[@class="entry-title"]/a' #FIXME? - Or fix LinkExtractor / use custom parse() method
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'entry-content'
  article:
    content:
      select-method: 'xpath'
      select-expression: '//div[@class="entry-content"]'
      match-rule: 'first'
    title:
      select-method: 'xpath'
      select-expression: '//meta[@property="og:title"]/@content'
      match-rule: 'first'
    publication_datetime:
      select-method: 'xpath'
      select-expression: '//meta[@property="article:published_time"]/@content'
      match-rule: 'first'
      datetime-format: 'YYYY-MM-DD'

globalresearch.ca:
  site_name: 'globalresearch.ca'
  start_url: 'http://globalresearch.ca/latest-news-and-top-stories'
  follow_url_path: 'latest-news-and-top-stories/page/'
  article_url_xpath: '//strong[@class="title"]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'content'
  article:
    content:
      select-method: 'xpath'
      select-expression: '//div[@itemprop="articleBody"]'
      match-rule: 'single'
    title:
      select-method: 'xpath'
      select-expression: '//h2[@itemprop="headline"]/text()'
      match-rule: 'single'
    byline:
      select-method: 'xpath'
      select-expression: '//meta[@itemprop="author"]/@content'
      match-rule: 'first'
    publication_datetime:
      select-method: 'xpath'
      select-expression: '//meta[@property="article:published_time"]/@content'
      match-rule: 'single'
      datetime-format: 'YYYY-MM-DD'

henrymakow.com:
  site_name: 'henrymakow.com'
  start_url: 'http://henrymakow.com/archives.html'
  follow_url_path: 'category/politics/page/'
  article_url_xpath: '//p[not(@class)]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'text-body'
  article:
    content:
      select-method: 'xpath'
      select-expression: '//div[@class="text-body"]'
      match-rule: 'single'
      warn-if-missing: 'False'
    title:
      select-method: 'xpath'
      select-expression: '//meta[@property="og:title"]/@content'
      match-rule: 'single'

prisonplanet.com:
  site_name: 'prisonplanet.com'
  start_url: 'http://prisonplanet.com/section/featured-stories/'
  follow_url_path: 'section/featured-stories/page/'
  article_url_xpath: '//div[@class="nArchiveHeader"]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'subarticle'
  article:
    content:
      select-method: 'xpath'
      select-expression: '//div[@class="subarticle"]'
      match-rule: 'single'
    title:
      select-method: 'xpath'
      select-expression: '//meta[@property="og:title"]/@content'
      match-rule: 'single'

madworldnews.com:
  site_name: 'madworldnews.com'
  start_url: 'http://madworldnews.com/politics/'
  follow_url_path: 'politics/page/'
  article_url_xpath: '//h3[contains(concat(" ", normalize-space(@class), " "), " entry-title ")]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'entry-content'
  article:
    content:
      select-method: 'xpath'
      select-expression: '//div[@id="main-content"]'
      match-rule: 'single'
    title:
      select-method: 'xpath'
      select-expression: '//meta[@property="og:title"]/@content'
      match-rule: 'first'
    byline:
      select-method: 'xpath'
      select-expression: '//span[@class="entry-meta-author author vcard"]//a/text()'
      match-rule: 'single'
    publication_datetime:
      select-method: 'xpath'
      select-expression: '//meta[contains(concat(" ", normalize-space(@property), " "), " article:published_time ")]/@content'
      match-rule: 'single'

thinkprogress.org:
  site_name: 'thinkprogress.org'
  start_url: 'http://thinkprogress.org'
  follow_url_path: 'politics/page/'
  article_url_xpath: '//h2[contains(concat(" ",normalize-space(@class)," ")," post__title ")]/a'
  article_search: 'paged'
  article:
    content:
      select-method: 'xpath'
      select-expression: '//div[@class="post__content"]'
      match-rule: 'single'
    title:
      select-method: 'xpath'
      select-expression: '//meta[@property="og:title"]/@content'
      match-rule: 'single'
    byline:
      select-method: 'xpath'
      select-expression: '//span[@class="post__byline__author"]//a/text()'
      match-rule: 'single'
    publication_datetime:
      select-method: 'xpath'
      select-expression: '//time[@class="post__date"]/@datetime'
      match-rule: 'single'


dailykos.com:
  site_name: 'dailykos.com'
  start_url: 'http://dailykos.com'
  follow_url_path: '\?page=\d*'
  article_url_xpath: '//div[contains(concat(" ",normalize-space(@class)," ")," story-title ")]/a'
    content:
      select-method: 'xpath'
      select-expression: '//div[@class="story-intro story-content"]'
      match-rule: 'single'
  title:
      select-method: 'xpath'
      select-expression: '//meta[@property="og:title"]/@content'
      match-rule: 'single'
   byline:
      select-method: 'xpath'
      select-expression: '//span[@class="post__byline__author"]//a/text()'
      match-rule: 'single'
